#! /bin/bash

#TODO --help: show n exit

helper() {
    echo "Helper output"
}

ACTIONS=()

while getopts ":c:a:s:" param; do
    case $param in
        c)
            c=$OPTARG;; #Directorio a monitorear cambios
        a)
            a=$OPTARG #Acciones a tomar con los cambios
            IFS=',' read -r -a ACTIONS <<< "$a";;
        s)
            s=$OPTARG;; #Directorio de salida
        *)
            helper;;
    esac
done

unset IFS;

actionHandler() {

    while read IN; do
        if [[ "$IN" == *"$c"* ]]; then
            FILENAME=$(echo "$IN" | awk '{print $1$3}')
            if [[ "${ACTIONS[*]}" =~ "listar" ]]; then
                listar $FILENAME
            fi
    
            if [[ "${ACTIONS[*]}" =~ "peso" ]]; then
                peso $FILENAME
            fi

            if [[ "${ACTIONS[*]}" =~ "compilar" ]]; then
                compilar $c; 
                if [[ "${ACTIONS[*]}" =~ "publicar" ]]; then
                    publicar $s;
                fi
            fi
        else
            echo "daemon output $IN"
        fi
    done
}

listar() {
    echo "File: $1"
}

peso() {
    if test -f "$i"; then
        echo "Size: "
        wc -c < "$i"
    fi
}

compilar() {
    #if file exist remove
    if [[ -e ./bin/output.txt ]]; then
        rm ./bin/output.txt
    fi
    #create output file
    mkdir -p ./bin
    touch ./bin/output.txt
    
    find $1 -type f -name '*' -exec cat {} + >> './bin/output.txt';
}

publicar() {
    cp ./bin/output.txt $1;
}

inotifywait -m -r -e create,modify,delete $c | actionHandler &
